### ISSUE TITLE
All screenshots are displayed in English language instead of the right ones

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhoneCompanion#3]
On the screenshots page: [Screenshots](https://github.com/UriahShaulMandel/BaldPhoneScreenshots), The screenshots of every language are displayed in english language, instead of the correct ones .

**Comment by UriahShaulMandel** [comment]
Hi, due to a google library-related bug, currently screenshots in different languages don't work.
It'll be fixed soon tho, check out this:
https://github.com/YarikSOffice/LanguageTest/issues/6#issuecomment-539536936
Note: the workaround had issues with BaldPhone, so I'll just wait to 1.1.1 which should be out soon :)
